import { ScanResult } from "@/hooks/useResourceScanner";

function formatDate() {
  return new Date().toISOString().split("T")[0];
}

function threatLabel(level: string): string {
  const labels: Record<string, string> = {
    None: "Safe",
    Low: "Low Risk",
    Medium: "Moderate Risk",
    High: "High Risk",
    Critical: "Critical Danger",
  };
  return labels[level] || level;
}

function threatBadgeClass(level: string): string {
  if (level === "High" || level === "Critical") return "critical";
  if (level === "Medium") return "medium";
  return "low";
}

export function exportScanAsPdf(result: ScanResult) {
  const indicators = (result.malicious_indicators ?? [])
    .map((i) => `<li>${i}</li>`)
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Threat Analysis Report — Vistahand AI</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 22px; margin-bottom: 4px; color: #0f172a; }
    h2 { font-size: 14px; margin: 24px 0 8px; text-transform: uppercase; letter-spacing: 1px; color: #3b82f6; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
    p, li { font-size: 13px; margin-bottom: 8px; }
    ul { padding-left: 20px; }
    .meta { font-size: 11px; color: #64748b; margin-bottom: 24px; }
    .badge { display: inline-block; font-size: 12px; font-weight: 700; padding: 2px 10px; border-radius: 4px; }
    .badge.critical { background: #fee2e2; color: #991b1b; }
    .badge.medium { background: #fef3c7; color: #92400e; }
    .badge.low { background: #dcfce7; color: #166534; }
    .score-bar { height: 12px; border-radius: 6px; background: #e2e8f0; margin: 8px 0 4px; }
    .score-fill { height: 100%; border-radius: 6px; }
    .score-fill.low { background: #22c55e; }
    .score-fill.medium { background: #eab308; }
    .score-fill.high { background: #ef4444; }
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Threat Analysis Report</h1>
  <p class="meta">Generated ${formatDate()} · Vistahand AI — Cyber Intelligence Platform</p>

  <h2>Verdict</h2>
  <p><span class="badge ${threatBadgeClass(result.threat_level)}">${threatLabel(result.threat_level)}</span></p>

  <h2>Risk Score</h2>
  <div class="score-bar">
    <div class="score-fill ${(result.probability ?? 0) <= 30 ? "low" : (result.probability ?? 0) <= 60 ? "medium" : "high"}" style="width: ${result.probability ?? 0}%"></div>
  </div>
  <p><strong>${result.probability ?? 0}%</strong> — ${(result.probability ?? 0) <= 10 ? "Very unlikely to cause harm" : (result.probability ?? 0) <= 30 ? "Unlikely, but stay alert" : (result.probability ?? 0) <= 50 ? "Possible — proceed with caution" : (result.probability ?? 0) <= 75 ? "Likely dangerous" : "Almost certain threat"}</p>

  ${result.attack_type ? `<h2>What Was Found</h2><p>${result.attack_type}</p>` : ""}

  ${indicators ? `<h2>Warning Signs</h2><ul>${indicators}</ul>` : ""}

  ${result.mitigation ? `<h2>Recommended Actions</h2><p>${result.mitigation}</p>` : ""}

  ${result.mitre_mapping ? `<h2>Technical Reference</h2><p><strong>MITRE ATT&CK:</strong> ${result.mitre_mapping}</p><p><strong>Threat Level:</strong> ${result.threat_level}</p>` : ""}

  <div class="footer">Report generated by Vistahand AI — Cyber Intelligence Platform · support@vistahand.com</div>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 300);
  }
}
