import { CveResult } from "@/hooks/useCveAnalysis";

function formatDate() {
  return new Date().toISOString().split("T")[0];
}

export function exportCveAsMarkdown(cve: CveResult) {
  const md = `# CVE Analysis Report: ${cve.cve_id}

**Generated:** ${formatDate()}  
**Tool:** Vistahand AI — Cyber Intelligence Platform

---

## Summary

${cve.summary}

## Exploitation Likelihood

**${cve.exploitation_likelihood}**

## Affected Systems

${cve.affected_systems}

## Mitigation & Patch Guidance

${cve.mitigation}

---

*Report generated by Vistahand AI*
`;

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${cve.cve_id}-report-${formatDate()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportCveAsPdf(cve: CveResult) {
  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${cve.cve_id} — CVE Analysis Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 40px; color: #1a1a2e; line-height: 1.6; max-width: 800px; margin: 0 auto; }
    h1 { font-size: 22px; margin-bottom: 4px; color: #0f172a; }
    h2 { font-size: 14px; margin: 24px 0 8px; text-transform: uppercase; letter-spacing: 1px; color: #3b82f6; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
    p { font-size: 13px; margin-bottom: 8px; }
    .meta { font-size: 11px; color: #64748b; margin-bottom: 24px; }
    .badge { display: inline-block; font-size: 12px; font-weight: 700; padding: 2px 10px; border-radius: 4px; background: #fef3c7; color: #92400e; }
    .badge.critical { background: #fee2e2; color: #991b1b; }
    .badge.high { background: #fee2e2; color: #991b1b; }
    .badge.medium { background: #fef3c7; color: #92400e; }
    .badge.low { background: #dcfce7; color: #166534; }
    .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${cve.cve_id}</h1>
  <p class="meta">CVE Analysis Report · Generated ${formatDate()} · Vistahand AI</p>

  <h2>Summary</h2>
  <p>${cve.summary}</p>

  <h2>Exploitation Likelihood</h2>
  <p><span class="badge ${cve.exploitation_likelihood.toLowerCase()}">${cve.exploitation_likelihood}</span></p>

  <h2>Affected Systems</h2>
  <p>${cve.affected_systems}</p>

  <h2>Mitigation & Patch Guidance</h2>
  <p>${cve.mitigation}</p>

  <div class="footer">Report generated by Vistahand AI — Cyber Intelligence Platform</div>
</body>
</html>`;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    // Give it a moment to render, then trigger print dialog (Save as PDF)
    setTimeout(() => printWindow.print(), 300);
  }
}
