project_id = "pznnokkhjpszacwiqybb"

[functions.analyze-threat]
verify_jwt = false

[functions.analyze-resource]
verify_jwt = false

[functions.analyze-cve]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
